# Generated by Django 3.1.3 on 2020-11-18 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('data', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data')),
                ('status', models.CharField(choices=[('V', 'Em Validação'), ('A', 'Aprovado'), ('N', 'Negado')], max_length=1, verbose_name='Status')),
                ('percentual_cashback', models.FloatField(blank=True, verbose_name='Percentual Cashback')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
